### ISSUE TITLE
MOLPay Payment Methods missing in Prestashop 1.7

### ISSUE THREAD

**Issue by tjwoon** [MOLPay/Prestashop_Plugin#11]
I am unable to find any MOLPay payment method in Prestashop Admin Portal's Payment Methods page.

## Version Info

MOLPay plugin version: v2.2.8

Prestashop Version: 1.7

## Steps to Reproduce:

1. Upload the unzipped `molpay` folder into the Prestashop `modules` folder.
2. In Prestashop admin portal's Modules page, search for MOLPay.
3. Click "Install" on the MOLPay plugin.
4. Go to Installed Modules page and look for MOLPay.
5. Manually configure Merchant ID by inserting `MOLPAY_MERCHANT_ID` row into Prestashop configuration table (saving via Prestashop admin portal does not work. See issue #10)
6. Manually configure Merchant Verify Key by inserting `MOLPAY_MERCHANT_VKEY` row into Prestashop configuration table
7. Manually enable Credit Card payment option by inserting `credit_on` row into Prestashop configuration table (with value = '1').
8. Go to Prestashop Admin Portal's Payment Methods page.
9. There is no "Credit Card", "Maybank", or any MOLPay payment method.

**Comment by syamimiaziah** [comment]
Hi @tjwoon 
The payment method selection of this plugin are not in Payment > Payment Method section. It is in the same section as configuring the merchant account detail (Modules > Modules & Services > Installed modules > Configure - MOLPay module). There will be list of check box for choosing a payment method. I have add you on Skype to assist on this matter.
![tets](https://user-images.githubusercontent.com/26619329/28009185-179f4d70-658d-11e7-807c-e0d7dafa23d3.JPG)

**Comment by tjwoon** [comment]
Hi @syamimiaziah , thanks for the response. In that case this issue is resolved, but #10 still does not work.
