### ISSUE TITLE
Outdated or incorrect documentation - "MERCHANT PROFILE" menu not found

### ISSUE THREAD

**Issue by tjwoon** [MOLPay/Prestashop_Plugin#4]
I am stuck at the last step of the "seamless" installation guide for [Prestashop 1.6.0.x](https://github.com/MOLPay/Prestashop_Plugin/wiki/Installation-Seamless-for-Prestashop-version-1.6.0.x-and-above).

```
Click on the MERCHANT PROFILE menu. Fill in return URL and Callback URL with your shopping cart URL.
```

There is no `MERCHANT PROFILE` menu in my Prestashop Admin page. I am using 1.6.0.14.

**Comment by tekjau** [comment]
@vespazwan  pls help @tjwoon on this

**Comment by vespazwan** [comment]
Hi @tjwoon,

Sorry for the late reply. The MERCHANT PROFILE is not at Prestashop, Its MOLPay Merchant Profile( https://www.onlinepayment.com.my/MOLPay/ ), at Merchant Profile Tab. To set all URL accordingly.

**Comment by tjwoon** [comment]
@vespazwan thank you.
