### ISSUE TITLE
your payment info not correct

### ISSUE THREAD

**Issue by li9ht** [MOLPay/Prestashop_Plugin#5]
Seemless plugin return "your payment info not correct" when selecting banks. 
However everything works fine where using the other plugin. 

prestashop version 1.6.0.11

**Comment by vespazwan** [comment]
Hi @li9ht ,

Yes , we got the report from our support team. But I already try by my own there is no problem. Can you provide link to testing and admin access for me to check the setting if possible. You can send details to this email technical@molpay.com . Thank You
