### ISSUE TITLE
return url error

### ISSUE THREAD

**Issue by li9ht** [MOLPay/Prestashop_Plugin#6]
after successfull payment user will be directed to 
www.domain.com/index.php?fc=module&module=molpay&controller=validation&gotoorder=3 
and will always display ->
Cart cannot be loaded or an order has already been placed using this cart

**Comment by drglnx** [comment]
Which prestashop version do you use? I just tested with newly installed version, it works fine.

**Comment by li9ht** [comment]
im using prestashop version 1.6.0.14 
im using "Prestashop version 1.5.6.x/1.6.0.x and above" module

**Comment by drglnx** [comment]
Did you correctly put Return URL as below ?

Return URL : http://xxxxxxxxxxxxxx/index.php?fc=module&module=molpay&controller=validation

**Comment by li9ht** [comment]
yes i did.
return url : index.php?fc=module&module=molpay&controller=validation
notification : index.php?fc=module&module=molpay&controller=notification_ipn
callback : index.php?fc=module&module=molpay&controller=callback_ipn

**Comment by li9ht** [comment]
i trace the error and it is cause by the 
controllers/front/validation.php 
line 80 
method $this->module->validateOrder
something went wrong there

**Comment by mohdhafeezjohari** [comment]
Hi li9th,

"im using prestashop version 1.6.0.14"
I tried exactly as your setup, but couldn't reproduced that error.
Is you website live? May I have link to it?

**Comment by li9ht** [comment]
@mohdhafeezjohari  https://ammara.com.my/shop
currently on catalog mode. so you cant make an order. this one is using version 1.6.0.9

**Comment by mohdhafeezjohari** [comment]
@li9ht The issue you mentioned about the return URL error, is that 1.6.0.14 or 1.6.0.9? 

I need to reproduce the error so that I can have a look at it.

**Comment by li9ht** [comment]
1.6.0.9

**Comment by mohdhafeezjohari** [comment]
Hi @li9ht, seems that I can't reproduce the error that you mentioned above. Can you provide me admin access to your prestashop, so that I can have a look through it. You can email it here, technical@molpay.com

**Comment by li9ht** [comment]
@mohdhafeezjohari  sent.. Thank you
