### ISSUE TITLE
Latest module does not support call back IPN

### ISSUE THREAD

**Issue by swankiat** [MOLPay/Prestashop_Plugin#8]
Hi,

I have added callback url in MOLPay admin however when you check the URL it is invalid.

I think the reason is we did not add callback controller in the module.

Please advice. Thanks.

**Comment by omarmahdzan** [comment]
Hi,

Apologize for issue that you experience. In order to further assist you, please e-mail support[at]molpay.com with the detail of your problem and your merchant ID.

Thanks.
